Configure for Unix.map_file / Bigarray.Genarray.map_file
c-cube/ocaml-bigstring pull request #6
Opened 2019-10-09 08:42 UTC by madroach

Add compatibility for new OCaml releases where ``map_file`` has moved to the ``Unix`` module and specialised ``Bigarray.Array[123]`` variants have been removed.
Stay compatible with older OCaml releases.

2019-10-09 14:46 UTC, c-cube commented on bigstring-unix.opam
> +  "dune" {>= "1.11"}
why is this needed?

2019-10-09 14:46 UTC, c-cube commented on configure.ml
> +let () =
nice, it'd be cleaner to put it somewhere in src/ to avoid cluttering the top directory, if possible :)

2019-10-09 14:47 UTC, c-cube requested changes
Really good contribution, thank you. Just a few comments :+1: .

2019-10-10 09:52 UTC, madroach commented on bigstring-unix.opam
> +  "dune" {>= "1.11"}
```
File "src/dune", line 2, characters 1-29:                 
2 |  (target bigstring_compat.ml)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: 'target' is only available since version 1.11 of the dune language
```

2019-10-10 09:57 UTC, madroach commented on configure.ml
> +let () =
done

2019-10-10 13:28 UTC, c-cube commented on bigstring-unix.opam
> +  "dune" {>= "1.11"}
does `targets` work? :)

2019-10-10 14:28 UTC, merged